# Generated by Django 3.2.6 on 2021-08-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=50)),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bachata_app.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Workshops'), (2, 'Festival'), (3, 'Party')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bachata_app.city')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bachata_app.organizer')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bachata_app.trainers')),
            ],
        ),
    ]
