# Generated by Django 3.2.6 on 2021-08-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachata_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='trainer',
        ),
        migrations.AddField(
            model_name='events',
            name='trainer',
            field=models.ManyToManyField(to='bachata_app.Trainers'),
        ),
    ]
