# Generated by Django 3.2.6 on 2021-08-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bachata_app', '0003_auto_20210821_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bachata_app.eventtypes'),
        ),
    ]
