# Generated by Django 3.2.6 on 2021-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachata_app', '0005_auto_20210822_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.IntegerField(choices=[(1, 'Workshops'), (2, 'Festival'), (3, 'Party')]),
        ),
        migrations.DeleteModel(
            name='EventTypes',
        ),
    ]
