# Generated by Django 3.2.6 on 2021-08-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachata_app', '0006_auto_20210822_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='trainer',
            field=models.ManyToManyField(blank=True, null=True, to='bachata_app.Trainers'),
        ),
    ]
